Fix some memory issues at cleanup
Running p3dfft::cleanup() using the address sanitizer
(https://en.wikipedia.org/wiki/AddressSanitizer) showed a few issues
when deleting instances of `trans_type1D`.

In this case (see build/init.C, around line 837), the destructor of
`gen_trans_type` was called instead of the `trans_type1D` destructor,
causing the following error from address sanitizer:

ERROR: AddressSanitizer: new-delete-type-mismatch on 0x60700001cb80 in thread T0:
  size of the allocated type:   72 bytes;
  size of the deallocated type: 56 bytes.
  object passed to delete has wrong type:

This is solved by marking the `trans_type1D` destructor as virtual.

A second issue was that both destructors deleted the `name` string.
However, when a `trans_type1D` gets deleted, both destructors are
called, which lead to a "double free" corruption. This is solved by
deleting `name` only in the destructor of the base class.